### ISSUE TITLE
Dedicated upload button for each mime types.

### ISSUE THREAD

**Issue by lawukini** [flagrow/upload#10]
Purpose for this request is to give user-friendly for Flarum user want to upload file.

Dedicated fonticon button for each of these mime types: video, audio, image, pdf file.

Generic fonticon (attachment) button for another mime types support by upload extension.

Please take a look at Plush Flarum text editor for example:
![Plush Forum](https://plushforums.com/images/mobile/chromeless/android3@2x.png)

**Comment by Cu8eR** [comment]
I think it is not good idea - why to make it difficult, Flarum is a nice user friendly software with easy GUI

**Comment by Luceos** [comment]
I am also not too happy about this though. If you can get people to upvote this issue (either by adding reactions to your post or by commenting), I'll reconsider.
