### ISSUE TITLE
Images not showing, only $image text on beta-7

### ISSUE THREAD

**Issue by jrock17** [flagrow/upload#101]
- flagrow/upload extension version: 0.5.7
- flarum version: 0.1.0-beta.7
- Upload adapter causing issues: local

---

Uploads seems to work fine and I can see the uploaded files on my server. But in the post and preview, only the $image text is posted.

![2017-07-30_08-51-34](https://user-images.githubusercontent.com/1270524/28755208-5becbbf2-750a-11e7-9e1f-7f329f52d0d5.png)

**Comment by luceos** [comment]
I haven't been able to generate previews during post editing yet. Is that other post also not showing an upload?

**Comment by jrock17** [comment]
Yeah I know you are still working on previews. But my posts don't show images either. 

I can't get the images to show up although I see them on the server.

**Comment by luceos** [comment]
Can you share your mime type configuration? And the output of `php flarum info`?

**Comment by jrock17** [comment]
I was able to figure it out. I think I was missing some php packages after upgrading to 7.1. 

I've never been able to get php flarum info or php flarum clear:cache to run though. Maybe it's because I install flarum into root instead of a flarum folder.

Thanks for your help

**Comment by viishaw** [comment]
Thank you for your work, but I also encountered this problem, my picture is only after the upload $ image-xxx rather than directly show the way, how to solve it? Thanks again.

**Comment by rymdluo** [comment]
@jrock17 Could you share what php packages you were missing or what you changed to get your images to show up? I am having the same issue.
