### ISSUE TITLE
Watermark Images does not remember its saved setting

### ISSUE THREAD

**Issue by bikepost** [flagrow/upload#104]
- flagrow/upload extension version: <0.5.7>
- flarum version: 0.1.0-beta.7
- Upload ignores saved choice to disable Watermark Images

---

<img width="987" alt="22" src="https://user-images.githubusercontent.com/30053780/29179374-13ec9dc0-7da9-11e7-8f39-59a18eb19a04.png">

**Comment by luceos** [comment]
Fixed but no new version tagged yet @bikepost
