### ISSUE TITLE
Cant Upload

### ISSUE THREAD

**Issue by wumix** [flagrow/upload#105]
- flagrow/upload extension version: <0.5.7>
- flarum version: 0.1.0-beta.7
- Upload adapter causing issues: <eg local or imgur>

---
I test it in Debug Modus False not working when i make debug true than i become this error
<When i Make a New Upload:

```
POST http://smartgames.esy.es/api/flagrow/upload

<br />
<b>Fatal error</b>:  Uncaught Error: Class 'Ramsey\Uuid\Uuid' not found in /home/u825870850/public_html/vendor/flagrow/upload/src/Repositories/FileRepository.php:58
Stack trace:
#0 /home/u825870850/public_html/vendor/flagrow/upload/src/Commands/UploadHandler.php(94): Flagrow\Upload\Repositories\FileRepository-&gt;createFileFromUpload(Object(Symfony\Component\HttpFoundation\File\UploadedFile), Object(Flarum\Core\User))
#1 [internal function]: Flagrow\Upload\Commands\UploadHandler-&gt;Flagrow\Upload\Commands\{closure}(Object(Zend\Diactoros\UploadedFile), 0)
#2 /home/u825870850/public_html/vendor/illuminate/support/Collection.php(469): array_map(Object(Closure), Array, Array)
#3 /home/u825870850/public_html/vendor/flagrow/upload/src/Commands/UploadHandler.php(140): Illuminate\Support\Collection-&gt;map(Object(Closure))
#4 [internal function]: Flagrow\Upload\Commands\UploadHandler-&gt;handle(Object(Flagrow\Upload\Commands\Upload))
#5 /home/u825870850/public_html/vendor/illuminate/bus/Dispatcher.php(202): call_user_func(Array, Object(Flagrow\Uplo in <b>/home/u825870850/public_html/vendor/flagrow/upload/src/Repositories/FileRepository.php</b> on line <b>58</b><br />>
```

**Comment by luceos** [comment]
What version of PHP do you have and did you install using composer?

**Comment by wumix** [comment]
Yes i installed this via Composer on My Android.
And than i uploadet this to my Webserver.
I use PhP 7.0 and before PhP 7.1 on Booth the same Problem.

Love greetings

**Comment by luceos** [comment]
> And than i uploadet this to my Webserver.

How did you upload this? Most likely you only uploaded the `vendor/flagrow/upload` folder? You should upload the whole vendor folder.

**Comment by wumix** [comment]
I have installed flarum on my Android with many Extensions plus flagrow Upload after this i deleted the config.php Upload the complete flarum Installation on my web Server and installed it again. I cant find the failure can you help me?
