### ISSUE TITLE
Installing causes js error and break the page

### ISSUE THREAD

**Issue by lightpencil** [flagrow/upload#106]
- flagrow/upload extension version: <0.5.7>
- flarum version: 0.1.0-beta.7
- Upload adapter causing issues: can't display the page due to js error.
The main page showed no js version and admin page showed nothing and gave errors

![image](https://user-images.githubusercontent.com/19776029/29811265-6dee6b60-8cd5-11e7-9edf-03b8174b128b.png)
![image](https://user-images.githubusercontent.com/19776029/29811528-68996416-8cd6-11e7-9583-8c1bb1298860.png)

After removing the extension the site shows normally. 
Please help me. I have no idea how it happens as this site is a fresh installed one.

**Comment by luceos** [comment]
I need more information in order to help you.

- Did you clear the cache after installation? `php flarum cache:clear`
- What other extensions do you have installed? Can you ouput `php flarum info`?

Not sure this is related to this extension, but I'm willing to help you solve this asap.

**Comment by lightpencil** [comment]
Yes, I did clear the cache after installation and tried to reinstall several times. It didn't help.
  
The output of `php flarum info` is 

> Flarum core 0.1.0-beta.7
> PHP 7.1.7
> Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, ctype, curl, dom, filter, ftp, gd, gettext, hash, iconv, intl, json, mbstring, mcrypt, SPL, session, pcntl, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, pdo_mysql, shmop, SimpleXML, soap, sockets, mysqli, sysvsem, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, fileinfo
> EXT flarum-approval v0.1.0-beta.7
> EXT flarum-bbcode v0.1.0-beta.5
> EXT flarum-emoji v0.1.0-beta.6
> EXT flarum-english v0.1.0-beta.7
> EXT flagrow-upload 0.5.7
> EXT flarum-flags v0.1.0-beta.7
> EXT flarum-likes v0.1.0-beta.6
> EXT flarum-lock v0.1.0-beta.7
> EXT flarum-markdown v0.1.0-beta.5
> EXT flarum-mentions v0.1.0-beta.7
> EXT jsthon-simplified-chinese v0.1.0-beta.7
> EXT flarum-sticky v0.1.0-beta.7
> EXT flarum-subscriptions v0.1.0-beta.6
> EXT flarum-suspend v0.1.0-beta.7
> EXT flarum-tags v0.1.0-beta.8

Thanks.

**Comment by luceos** [comment]
Can you upload the following file, please:

```
vendor/flagrow/upload/js/admin/extension.js
```

**Comment by lightpencil** [comment]
The problem is that in this dir there is no such a file, I only got the following:

`Gulpfile.js   dist/         package.json  yarn.lock`

Thanks.

**Comment by lightpencil** [comment]
The attached file is in ZIP as Github doesn't support js upload.

[extension.zip](https://github.com/flagrow/upload/files/1260068/extension.zip)

**Comment by luceos** [comment]
Can you try installing dev-master of `flagrow/upload`?

```
composer require flagrow/upload:dev-master
```

I'd like to know whether that fixes your issue.

**Comment by lightpencil** [comment]
It's a weird problem, not solved, I'll try to reinstall Flarum.

**Comment by lightpencil** [comment]
Tried to reinstall Flarum and the problem still exists.
What should I do?
Is there anything/dependency that required to install?
I need some help.

**Comment by luceos** [comment]
I would love to take a look at your admin area, to be honest. Would you be able to join us on discord at https://flagrow.io/join-discord ? Otherwise send me an email, you can find the address in the composer.json of any of our extensions.

**Comment by luceos** [comment]
@lightpencil joined discord.

**Comment by lightpencil** [comment]
Thank you so much! Now it's working like a charm.

**Comment by luceos** [comment]
Issue resolved on discord. Related to rev-manifest.json not being deleted and possibly a stale cache from Cloudflare.
