### ISSUE TITLE
"code": "resource_not_found" }

### ISSUE THREAD

**Issue by bsed** [flagrow/upload#107]
- flagrow/upload extension version: <x.y.z>
- flarum version: 0.1.0-beta.6
- Upload adapter causing issues: <eg local or imgur>

---

![image](https://user-images.githubusercontent.com/10845087/29812263-9339f0d0-8cd8-11e7-833c-1bdda9421509.png)

see 
http://bbs.mbioq.com/d/6-cccc   ,,, http://bbs.mbioq.com/api/flagrow/download/316d8c4c-9cf0-4796-bbdc-394098288319/5/fkmwtV7c2PmoflpDzloF0B31WKPISYavh2FdAqw5  why?

**Comment by luceos** [comment]
If you don't take the time to complete the information we ask for, I'm unsure I'd like to take the time to resolve your issue. Although this sounds harsh, I'm no psychic and problem-solving is much easier without asking ten questions which we ask for initially anyway.

Please post the details of `php flarum info`.

Feel free to re-open once you've added the extension version information.

**Comment by bsed** [comment]
php flarum info 
```
Flarum core 0.1.0-beta.7
PHP 7.0.22
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, json, ldap, exif, mcrypt, mysqlnd, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flagrow-upload 0.5.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT jsthon-simplified-chinese v0.1.0-beta.7
EXT terabin-sitemap v1.0.2-beta.2
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: http://bbs.mbioq.com
Installation path: /var/www/nginx_html/html

```

you can use chrome audit that [6-cccc](http://bbs.mbioq.com/d/6-cccc)  view it,

my nginx config 
```
server {
    listen       80;
    server_name bbs.mbioq.com;
    root /var/www/nginx_html/html;
     
    index index.php index.html;
    
    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    location / {
       # root   /usr/share/nginx/html;
       # index  index.html index.htm;
 
       try_files $uri $uri/ /index.php?$query_string;
       
    }
  
   location /api {
    try_files $uri $uri/ /api.php?$query_string;
   }

   location /admin {
      try_files $uri $uri/ /admin.php?$query_string;
   }
 
    location /flarum {
      deny all;
      return 404;
    }
  
    location = /favicon.ico { log_not_found off; access_log off; }
    location = /robots.txt  { access_log off; log_not_found off; }  
  
    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}
 
   location ~ \.php$ {
        #root /var/www/nginx_html/html;
        try_files $uri =404;
        fastcgi_split_path_info ^(.+.php)(/.+)$;
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        #fastcgi_param  SCRIPT_FILENAME  /var/www/nginx_html/html$fastcgi_script_name;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include        fastcgi_params;
        #fastcgi_param HTTPS off;
  } 

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
  
   
    # Deny .htaccess file access
        location ~ /\.ht {
            deny all;
        }
       location ~* \.html$ {
            expires -1;
        }
        location ~* \.(css|js|gif|jpe?g|png)$ {
            expires 1M;
        }
        gzip on;
        gzip_http_version 1.1;
        gzip_vary on;
        gzip_comp_level 6;
        gzip_proxied any;
        gzip_types application/atom+xml \
                   application/javascript \
                   application/json \
                   application/vnd.ms-fontobject \
                   application/x-font-ttf \
                   application/x-web-app-manifest+json \
                   application/xhtml+xml \
                   application/xml \
                   font/opentype \
                   image/svg+xml \
                   image/x-icon \
                   text/css \
                   text/html \
                   text/plain \
                   text/xml;
        gzip_buffers 16 8k;
        gzip_disable "MSIE [1-6]\.(?!.*SV1)";
}


```

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/29850047-5679f64c-8d5d-11e7-9782-5583ae49d6d8.png)

**Comment by luceos** [comment]
If hotlink protection is enabled, can you disable it and see if downloading works?

**Comment by bsed** [comment]
I see what affect help, other plug-ins have not encountered such a problem, the picture is passed up, but when you click the view to find

**Comment by bsed** [comment]
see this 
![image](https://user-images.githubusercontent.com/10845087/29859229-ad5bdf3a-8d93-11e7-9a65-6c491dbb0d12.png)
when i check  hotlink,  When you click the diagram, you will automatically download it instead of the new page see this  http://bbs.mbioq.com/d/6--

**Comment by luceos** [comment]
I have a hard time understanding you, my apologies. Can you give a clear answer to the following:

> Does downloading work if hotlink protection is disabled?

**Comment by bsed** [comment]
is ok， this pic can download .

**Comment by clarkwinkelmann** [comment]
I'm not sure I understand which issue you are reporting exactly @bsed 

I just tried your website.

- The thumbnail shows and it's possible to do right right > show background image without any issue
- Download button does not work. A 401 empty response is returned

The response comes from Flarum so it's most likely not related to the webserver configuration.

**Comment by bsed** [comment]
Oh, I can't help it. Hopefully flarum can solve this problem， xiexie .

**Comment by bsed** [comment]
My switch from nginx to apche2 is still the same problem @clarkwinkelmann @luceos

**Comment by luceos** [comment]
We don't know what your issue is, because you aren't answering any of our questions 😞 :

- Does downloading work if hotlink protection is disabled?
- I'm not sure I understand which issue you are reporting exactly.

Even though I ask you to invest a bit more time, could you please clarify the issue you run into?

**Comment by bsed** [comment]
when i close hotlink, and visit web, click button, The picture file will be downloaded automatically

**Comment by bsed** [comment]
I am in the background to close the anti-theft chain protection, click on the front page, the picture file will automatically download. Can not be viewed on new pages,
我在后台关闭防盗链保护后，在前台点击页面， 图片文件会自动下载。不能够在新页面查看，

**Comment by luceos** [comment]
Yes when clicking a preview picture in your forum it will redirect you to download that file. That is intended. You can install 0.6.0-beta to change how uploaded files are shown.

**Comment by bsed** [comment]
Do I have to downgrade to 0.6.0-beta?

**Comment by luceos** [comment]
I'm not referring to flarum, I am referring to this extension:

https://discuss.flarum.org/d/4154-flagrow-upload-the-intelligent-file-attachment-extension/354

**Comment by bsed** [comment]
i have downgrade to 0.6.0-beta ,
```bash
composer require flagrow/upload:0.6.* --prefer-dist --update-no-dev -o
php flarum cache:clear
rm assets/rev-manifest.json
```
I uploaded JPG pictures through the foreground page,  tips error， why ?

**Comment by clarkwinkelmann** [comment]
What do you mean by "foreground page" ? Are you sure you're whitelisting this file type in the admin page ?

**Comment by bsed** [comment]
in admin dashboard , file mime type is `((image|audio|video)\/.*)|(application\/pdf)`

**Comment by bsed** [comment]
@clarkwinkelmann

**Comment by bsed** [comment]
can not solve the closed @luceos

**Comment by luceos** [comment]
@bsed seems your file was not of image audio or video mime type.

**Comment by bsed** [comment]
My file format is jpg

**Comment by bsed** [comment]
My server side configuration is fine

**Comment by luceos** [comment]
I just configured the mime type regex you mentioned above and uploaded a jpeg without issue:

![image](https://user-images.githubusercontent.com/504687/30019060-90e1a7d4-915f-11e7-9d4a-01398c18d3b0.png)

**Comment by luceos** [comment]
Can you share the file you tried uploading?

**Comment by bsed** [comment]
enen ,yes 
![tim 20170828162101](https://user-images.githubusercontent.com/10845087/30019559-9928abc0-9193-11e7-84d3-01989f49d74b.jpg)

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/30019585-b16cab28-9193-11e7-8f2f-0a3740827e18.png)

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/30019609-cb4bb836-9193-11e7-8624-235c2548c30c.png)

**Comment by bsed** [comment]
If you can upload this picture over there, I can send it to your mailbox and try again

**Comment by luceos** [comment]
Works for me 😁 

![image](https://user-images.githubusercontent.com/504687/30019887-50a464c4-9162-11e7-9dce-7b263451c439.png)

I'm unsure where this comes from. Can you play around by disabling the resize and the watermarking?

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/30020046-1a361da0-9195-11e7-8b09-f59a2683110d.png)
i have disabling the resize and the watermarking, but still can not upload pictures, can you tell me your flarum version?

**Comment by bsed** [comment]
[root@jdu4e00u53f7 html]# php flarum info
Flarum core 0.1.0-beta.7
PHP 7.0.22
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, imagick, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, json, ldap, exif, mcrypt, mysqlnd, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flagrow-upload 0.6.0-beta
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT jsthon-simplified-chinese v0.1.0-beta.7
EXT terabin-sitemap v1.0.2-beta.2
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: http://bbs.mbioq.com
Installation path: /var/www/nginx_html/html

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/30095067-b828f08c-9302-11e7-8e6c-c10c32630706.png)
oh, ok . hah

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/30095099-eeacb198-9302-11e7-84e6-64cec44b313a.png)

**Comment by bsed** [comment]
![image](https://user-images.githubusercontent.com/10845087/30095161-58128860-9303-11e7-99e5-361a074bd33c.png)
![image](https://user-images.githubusercontent.com/10845087/30095163-5e2a809a-9303-11e7-99f3-55ad44001d37.png)

**Comment by bsed** [comment]
@luceos @clarkwinkelmann  thank you ~. You need to downgrade before you upgrade  see https://discuss.flarum.org/d/4154-flagrow-upload-the-intelligent-file-attachment-extension/354
