### ISSUE TITLE
Uploads don't work on mobile

### ISSUE THREAD

**Issue by jrock17** [flagrow/upload#109]
- flagrow/upload extension version: 0.6.0-beta
- flarum version: 0.1.0-beta.6
- Upload adapter causing issues: both

---

Uploads don't seem to work on mobile view in the latest version. If you click the button, nothing happens.

**Comment by jrock17** [comment]
My users that were complaining about this issue say it's working for them now. I saw the issue myself but it went away after a day.

Perhaps it was a caching issue with the mobile browser. Feel free to close this issue.

**Comment by luceos** [comment]
I'm so happy this is not a bug :P
