### ISSUE TITLE
Upload returns 500 because of "Unknown column 'uuid' in 'where clause'"

### ISSUE THREAD

**Issue by Hekmon** [flagrow/upload#110]
- flagrow/upload extension version: 0.5.7 (upgraded from 0.4.13 after flarum upgrade from 0.1.0-beta6 to 0.1.0-beta7)
- flarum version: 0.1.0-beta.7
- Upload adapter causing issues: local

---

It seems a mysql table column is missing, probably from the flarum and/or upload extension upgrade ?

```POST https://daltons.stationem.net/api/flagrow/upload

{
  "errors": [
    {
      "code": 500,
      "title": "Internal server error",
      "detail": "PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uuid' in 'where clause' in /home/nginx/flarum_daltons/vendor/illuminate/database/Connection.php:319\nStack trace:\n#0```
```

Full log attached as well as the `flagrow_files` table description : [logs.zip](https://github.com/flagrow/upload/files/1275028/logs.zip)

Weird thing is, some image files work, other don't :/

**Comment by luceos** [comment]
Run `php flarum migrate`

**Comment by Hekmon** [comment]
It worked !

I did the php flarum migrate but only after upgrading flarum (upload was not upgraded at that time), then I tried the `composer update flagrow/upload && php flarum cache:clear` which did not upgrade the upload extension. I ended up relaunching the `composer require flagrow/upload && php flarum cache:clear` to finally have the last version of upload but I was not aware the it needed too the `php flarum migrate`.

Thanks :)

**Comment by luceos** [comment]
No problem, glad it worked out ;)
