### ISSUE TITLE
Switch to https

### ISSUE THREAD

**Issue by sulf1ron** [flagrow/upload#115]
- flagrow/upload extension version: latest
- flarum version: latest
- Upload adapter causing issues: local

---
I used to use HTTP, and now I switched to https.
But the thumb is displayed using HTTP.
Is it a problem already existing?
Or is it because the switching from http to https?
Thanks.

**Comment by luceos** [comment]
> Or is it because the switching from http to https?

Yes.

Solution: rewrite requests to your forum to https using htaccess or webserver configuration.

I can't suggest any other solution because you haven't specified the extension version you are on.

**Comment by sulf1ron** [comment]
I wrote "latest" inside <> and it didn't display.
I use the latest version of both flagrow/upload and flarum.

**Comment by luceos** [comment]
What latest of upload? Because there's version 0.5.7 and 0.6.0-beta; they make a world of a difference..

**Comment by sulf1ron** [comment]
Sorry for that.
I use version 0.5.7
You can find an example at https://japari.club/d/61-friends
Thumbnails are displayed using http but not https.

**Comment by luceos** [comment]
Warning, this is untested, make a backup before you run this query on your production database!!

```sql
UPDATE posts SET content = replace(content, 'http://japari.club/','https://japari.club/');
```

Run this on the Flarum database.

Inspiration by https://blog.templatetoaster.com/update-old-urls-in-database/

**Comment by sulf1ron** [comment]
I‘ll tell you the result after backup and try.

**Comment by sulf1ron** [comment]
Success!
Maybe it can be added to the next version?

**Comment by luceos** [comment]
Well.. no. You decided to switch to https. The extension has no influence over the URL you use. I'll consider this for a FAQ though.

Good thing it worked!
