### ISSUE TITLE
Flagrow Upload doesn't work with php < 7

### ISSUE THREAD

**Issue by pflstr** [flagrow/upload#117]
- flagrow/upload extension version: 0.6.0-beta
- flarum version: 0.1.0-beta.7
- PHP 5.6.30
- Upload adapter causing issues: local

---

The issue was reported here: https://discuss.flarum.org/d/4154/363

Trying to upload an image results in the following error:

```
POST http://domain.com/api/flagrow/upload

<br />
<b>Fatal error</b>:
Call to undefined function Flagrow\Upload\Templates\preg_replace_callback_array()
in <b>.../flarum/vendor/flagrow/upload/src/Templates/AbstractTemplate.php</b> 
on line <b>82</b><br />
```

It turns out, that `preg_replace_callback_array()` needs php7. The [documentation of preg_replace_callback_array()](http://php.net/manual/en/function.preg-replace-callback-array.php) shows a user comment suggesting a [workaround for older PHP versions](http://php.net/manual/en/function.preg-replace-callback-array.php#118563) using preg_replace_callback().

**Comment by luceos** [comment]
This was fixed in 0.6.0-beta. Feel free to upgrade or wait for a stable release.
