### ISSUE TITLE
scandir() has been disabled for security reasons in *****

### ISSUE THREAD

**Issue by Witype** [flagrow/upload#127]
Warning: scandir() has been disabled for security reasons in /home/wwwroot/j1-discuss/vendor/oyejorge/less.php/lib/Less/Cache.php on line 252

Fatal error: Uncaught RuntimeException: Output has been emitted previously; cannot emit response in /home/wwwroot/j1-discuss/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php:31 Stack trace: #0 /home/wwwroot/j1-discuss/vendor/zendframework/zend-diactoros/src/Response/SapiEmitter.php(27): Zend\Diactoros\Response\SapiEmitter->assertNoPreviousOutput() #1 /home/wwwroot/j1-discuss/vendor/zendframework/zend-diactoros/src/Server.php(162): Zend\Diactoros\Response\SapiEmitter->emit(Object(Zend\Diactoros\Response)) #2 /home/wwwroot/j1-discuss/vendor/flarum/core/src/Http/AbstractServer.php(36): Zend\Diactoros\Server->listen(Object(Zend\Stratigility\NoopFinalHandler)) #3 /home/wwwroot/j1-discuss/admin.php(16): Flarum\Http\AbstractServer->listen() #4 {main} thrown in /home/wwwroot/j1-discuss/vendor/zendframework/zend-diactoros/src/Response/SapiEmitterTrait.php on line 31

flarum version bete 0.1.0 dev.7

how to deal with this problem? thanks

**Comment by luceos** [comment]
This is unrelated to this package. This is related to flarum core. But even Flarum can't help you here because your hosting provider has limited the abilities on your server.
