### ISSUE TITLE
How to resolve a download file after http to https

### ISSUE THREAD

**Issue by gashmicky** [flagrow/upload#128]
- flagrow/upload extension version: <x.y.z>
- flarum version: 0.1.0-beta.6
- Upload adapter causing issues: <eg local or imgur>

---

my flagrow/upload version is 0.6.0 and when i copy the path from the database with both http and https it can able to download the file but from the application the following error appear {"errors":[{"code":500,"title":"Internal server error"}]}

**Comment by luceos** [comment]
Can you check `storage/logs/flarum.log`, please ignore all NotFound exceptions.

**Comment by gashmicky** [comment]
not clear message but the following is the log file that i got 

2018-02-19 07:52:29] production.DEBUG: Flarum\Http\Exception\MethodNotAllowedException in C:\wamp641\www\cop\vendor\flarum\core\src\Http\Middleware\DispatchRoute.php:65
Stack trace:
#0 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Dispatch.php(82): Flarum\Http\Middleware\DispatchRoute->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#1 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Next.php(113): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#2 C:\wamp641\www\cop\vendor\flarum\core\src\Http\Middleware\SetLocale.php(50): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#3 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Dispatch.php(82): Flarum\Http\Middleware\SetLocale->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#4 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Next.php(113): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#5 C:\wamp641\www\cop\vendor\flarum\core\src\Http\Middleware\AuthenticateWithSession.php(33): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#6 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Dispatch.php(82): Flarum\Http\Middleware\AuthenticateWithSession->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#7 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Next.php(113): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#8 C:\wamp641\www\cop\vendor\flarum\core\src\Http\Middleware\RememberFromCookie.php(38): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#9 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Dispatch.php(82): Flarum\Http\Middleware\RememberFromCookie->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#10 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Next.php(113): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#11 C:\wamp641\www\cop\vendor\flarum\core\src\Http\Middleware\StartSession.php(33): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#12 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Dispatch.php(82): Flarum\Http\Middleware\StartSession->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#13 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Next.php(113): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#14 C:\wamp641\www\cop\vendor\flarum\core\src\Http\Middleware\ParseJsonBody.php(30): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#15 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Dispatch.php(82): Flarum\Http\Middleware\ParseJsonBody->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#16 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\Next.php(113): Zend\Stratigility\Dispatch->__invoke(Object(Zend\Stratigility\Route), NULL, Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), Object(Zend\Stratigility\Next))
#17 C:\wamp641\www\cop\vendor\zendframework\zend-stratigility\src\MiddlewarePipe.php(75): Zend\Stratigility\Next->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response))
#18 C:\wamp641\www\cop\vendor\flarum\core\src\Http\AbstractServer.php(53): Zend\Stratigility\MiddlewarePipe->__invoke(Object(Zend\Stratigility\Http\Request), Object(Zend\Stratigility\Http\Response), NULL)
#19 C:\wamp641\www\cop\vendor\zendframework\zend-diactoros\src\Server.php(166): Flarum\Http\AbstractServer->__invoke(Object(Zend\Diactoros\ServerRequest), Object(Zend\Diactoros\Response), NULL)
#20 C:\wamp641\www\cop\vendor\flarum\core\src\Http\AbstractServer.php(34): Zend\Diactoros\Server->listen()
#21 C:\wamp641\www\cop\index.php(21): Flarum\Http\AbstractServer->listen()
#22 {main}

**Comment by luceos** [comment]
I see you're running beta 6. I really would love to support that version, but I cannot. Please upgrade to Flarum 0.1.0-beta.7.1.
