### ISSUE TITLE
I can't able to download a file with https even if i upgrade to beta 7 

### ISSUE THREAD

**Issue by gashmicky** [flagrow/upload#130]
- flagrow/upload extension version: <x.y.z>
- flarum version: 0.1.0-beta.6
- upload adapter causing issues: <eg local or imgur>
- mimetype configurations: <eg .* => local>

---

<type here..>

**Comment by luceos** [comment]
If you don't fill in the details we ask of you during issue creation, we won't be able to help you. We'd gladly assist you any way we can, once you do.

**Comment by gashmicky** [comment]
Sorry @luceos i didn't see any request when i was creating issue please assist me to get the space that i have to fill and want to continue to sort out my issue thank you very mach.

**Comment by luceos** [comment]
![image](https://user-images.githubusercontent.com/504687/36669584-a7425ba2-1af5-11e8-80bc-c15d0d07cd8e.png)
