### ISSUE TITLE
how to upload an *.apk but wont rename to *.zip

### ISSUE THREAD

**Issue by DearTanker** [flagrow/upload#132]
- flagrow/upload extension version: <x.y.z>
- flarum version: 0.1.0-beta.6
- upload adapter causing issues: <eg local or imgur>
- mimetype configurations: <eg .* => local>

---

<type here..>

**Comment by luceos** [comment]
Feel free to re-open when you've added a description explaining what the problem at hand is. I'm not psychic and I hate to guess based off of an issue title.

**Comment by DearTanker** [comment]
reopen
