### ISSUE TITLE
Not compatible with beta 8

### ISSUE THREAD

**Issue by HLFH** [flagrow/upload#144]
- flagrow/upload extension version: master
- flarum version: 0.1.0-beta.8
---

I got the error Uncaught TypeError: Cannot read property 'default' of undefined in JS Console and nothing is loading besides the header.

**Comment by luceos** [comment]
Beta 8 is not released yet and there are still upcoming changes that affect the release. Running flarum beta 8 only makes sense as a developer working on your own extensions.

**Comment by luceos** [comment]
And yes this extensions wasn't yet made compliant yet.
