### ISSUE TITLE
Add support for CDN when using AWS S3

### ISSUE THREAD

**Issue by mattmezza** [flagrow/upload#149]
- flagrow/upload extension version: 0.6.0
- flarum version: 0.1.0-beta.6
- upload adapter causing issues: AWS S3
- mimetype configurations: .*

---

With https://github.com/flagrow/upload/pull/11/commits/5df28a7787d3e0f57f3cfa6eb4c5f2e1f772b790 support for CDN has been introduced. 

Anyways, when using AWS S3, this field is ignored in favour of a custom url built using the bucket name. 

I think we should give the user the control over the url for images and files (he might wanna move the bucket after a while or simply use a front cdn).

I propose to use the CDN field if set and build url for the resource with that value.

**Comment by luceos** [comment]
I'll wait for your PR; seems you're working on one 👍

**Comment by noriods** [comment]
When I try and use the CDN prefix, it strips the filename completely from the [upl ...] code.
