### ISSUE TITLE
Multiple uploads per post

### ISSUE THREAD

**Issue by yekenuk** [flagrow/upload#15]
Would it be possible to allow multiple uploads per post? Would be great if a member could select 10 images at once :)

Cheers! Keep up the great work.

**Comment by yekenuk** [comment]
Just to save them clicking the upload icon 10 times... they could instead click it once... select multiple images in the dialog... or select all... hit upload... All done...

There may not be a massive benefit, but I've already had two people asking for it... I know myself I like to open the dialog... sometimes select all and done...

Thanks again :)

**Comment by Luceos** [comment]
I think this requires a slight modification in the payload send and received and a slight edit to the upload input field.

**Comment by yekenuk** [comment]
Sounds good! :+1:

**Comment by Luceos** [comment]
@yekenuk this feature is available in `dev-multi` feel free to update your dependency and give it a test drive. I'll ship the feature with the next feature.

**Comment by yekenuk** [comment]
Great! Not being an expert on composer, just run:

composer update flagrow/upload

**Comment by Luceos** [comment]
edit your composer.json where it says `flagrow/upload` change the value after to `dev-multi` and then run `composer update`; please note that composer update is not something you want to do in a production/live environment :smile:

**Comment by yekenuk** [comment]
Ah cheers mate... 

I'm running flarum in a small production site ha :)

Thanks again! Keep up the great work

**Comment by Luceos** [comment]
Well - between us - you can change the dependency as proposed above, if you encounter issues, change it back and run the command again. Delete any `assets/*.js` to drop the cache.

**Comment by yekenuk** [comment]
Brilliant thanks.
