### ISSUE TITLE
Issue on upgrading to the new Beta 8

### ISSUE THREAD

**Issue by PeopleInside** [flagrow/upload#156]
The extension (Upload) was used in beta 0.1.0-beta.7.2.
before the upgrade i turned off from the extensions page.
 
When is installed again in Beta 8 broke the community and maybe the database.

If after installing using composer require "flagrow/upload:*"

So i try to remove it for have the community back because generate a blank page in the community but I see the following error in SSH:

Trait 'Flarum\Core\Access\AssertPermissionTrait' not found in vendor/flagrow/upload/src/Commands/DownloadHandler.php on line 21

I need to remove everything and restore the old backup as also remove the extension with composer doesn't restore the community back.

Need help to understand how migrate to the new Beta 8.

**Comment by luceos** [comment]
What version of upload do you have installed? Can you give the output of `php flarum info`?

**Comment by PeopleInside** [comment]
`Flarum core 0.1.0-beta.8 PHP version: 7.1.24 Loaded extensions: Core, date, libxml, pcre, dom, fileinfo, filter, hash, json, SPL, bz2, posix, Reflection, session, SimpleXML, standard, xml, xmlreader, xmlwriter, bcmath, openssl, calendar, ctype, curl, dba, mbstring, ftp, gd, gettext, gmp, iconv, imap, intl, ldap, exif, mcrypt, zlib, pcntl, PDO, pdo_sqlite, shmop, soap, sockets, sqlite3, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlrpc, xsl, zip, Phar, mysqlnd, mysqli, pdo_mysql, ionCube Loader, Zend OPcache +----------------------+-----------------+--------+ | Flarum Extensions | | | +----------------------+-----------------+--------+ | ID | Version | Commit | +----------------------+-----------------+--------+ | flarum-approval | v0.1.0-beta.8 | | | flarum-bbcode | v0.1.0-beta.8 | | | flarum-emoji | v0.1.0-beta.8 | | | flarum-flags | v0.1.0-beta.8 | | | flarum-likes | v0.1.0-beta.8 | | | flarum-lock | v0.1.0-beta.8 | | | flarum-markdown | v0.1.0-beta.8 | | | flarum-mentions | v0.1.0-beta.8 | | | flarum-sticky | v0.1.0-beta.8 | | | flarum-subscriptions | v0.1.0-beta.8 | | | flarum-suspend | v0.1.0-beta.8 | | | flarum-tags | v0.1.0-beta.8.1 | | | flarum-auth-facebook | v0.1.0-beta.8 | | | flarum-lang-english | v0.1.0-beta.8 | | | nearata-lang-italian | v0.1.0-beta.7.3 | | +----------------------+-----------------+--------+ Base URL: https://community.peopleinside.it/ Installation path: [...]community.peopleinside.it Debig mode: off`

**Comment by luceos** [comment]
Try running 

```bash
$ composer update flagrow/upload
```

I just tagged 0.7.0, it might not have been found due to being beta stability.

**Comment by PeopleInside** [comment]
Hi @luceos i will try in next hours or day. From this morning i dedicated 2 hours for try to upgrade to the new Beta. Resolved some issue now i need try to resolve the uploader issue but due to this i restored the previous beta and backups because installing uploader was broken everything. I will try to fix... i will update here and if solved i will close this issue.

Now i need to take a little break from the PC @.@
