### ISSUE TITLE
Support uploading images to Imgur.

### ISSUE THREAD

**Issue by waltdestler** [flagrow/upload#16]
I'm currently still using the Image Upload extension because it supports uploading images to Imgur. It'd be great if this extension could support that as well.

**Comment by Luceos** [comment]
I understand, drawback of imgur is that it's really just an image upload service. I'll have to look into this, a basic support for a "service per file type" setting is already in the code, but not yet completely done.

**Comment by Luceos** [comment]
https://github.com/flagrow/upload/tree/imgur

work in progress
