### ISSUE TITLE
how about add watermark option for images?

### ISSUE THREAD

**Issue by fingonpalantir** [flagrow/upload#17]
watermark for jpg/png images upload.

1.Position
top-left/right center bottom-left/right 
and with user's name who was uploaded it.
2. Transparency
3. font file path for non-western users and font size

thanks

**Comment by Luceos** [comment]
Sounds like a great idea. I'll put it on the roadmap, but not for the upcoming release if you don't mind.

**Comment by fingonpalantir** [comment]
no matter and thanks for your works.

I m still waiting for the stable version than I will give up xenforo.

**Comment by Luceos** [comment]
Started work on this.

**Comment by tony199555** [comment]
Is top left missing? I can see all other options except top left.

**Comment by Luceos** [comment]
https://github.com/flagrow/upload/commit/713b6c5d1d8102967a135566b987dde70246e979#diff-d1a3909f089a1c3c48cedf1dd5910883R46

**Comment by Luceos** [comment]
OOPS :D
