### ISSUE TITLE
[Sercurity Bug] Send all settings to frontend

### ISSUE THREAD

**Issue by oanhnn** [flagrow/upload#32]
## Reproduce
1. Open forum site, that is build from flarum/flarum
2. Open web browser console, and run console.log(app.forum.data.attributes);

## OR
1. Go to http://site.com/api/forum

## Issue
I see all settings from database, it include access key of some service, eg: AWS S3, .....

**Comment by Luceos** [comment]
Not sure why I missed that 👍 thanks will release a patched version asap.
