### ISSUE TITLE
Abstract Upload Adapter

### ISSUE THREAD

**Issue by dav-is** [flagrow/upload#34]
Considering the [local](https://github.com/flagrow/upload/blob/master/src/Adapters/Local.php) adapter accepts any filesystem it should be made into an abstract class. And a new Local adapter and the other adapters should extend the abstract one.

**Comment by Luceos** [comment]
Thanks, I already had the AWS adapter extend Local, so it only makes sense to make an abstract version.

**Comment by dav-is** [comment]
Since you're using an abstract class now, you shouldn't need to use the interface :)
