### ISSUE TITLE
S3 Upload file issue. : needs to be %3A

### ISSUE THREAD

**Issue by 0E800** [flagrow/upload#42]
Using Flarum Beta (current as of 1/12/2017)

Added S3 extension requirements.
Correctly added S3 creds.
Granted bucket privileges to Public.
When I upload an image, it (the image) does not display on the forum the output is:
image autopng.png(https://s3.us-west-2.amazonaws.com/oe800/2017-01-12/18:58:430-autopng.png)
(brackets removed)

The output needs to be changed.

https://s3.us-west-2.amazonaws.com/oe800/2017-01-12/18:58:430-autopng.png

to:

https://s3-us-west-2.amazonaws.com/oe800/2017-01-12/18%3A58%3A430-autopng.png

Notice the ':' is changed to '%3A' 

Is there a source file / location I can make the changes to? A package I am missing?

https://github.com/flagrow/upload/blob/master/src/Adapters/Flysystem.php I believe is the file to adjust.

    protected function generateFilename(File $file)
    {
        $today = (new Carbon());
        $file->path = sprintf(
            "%s/%s",
            $today->toDateString(),
            $today->toTimeString() . $today->micro . '-' . $file->base_name
        );
    }
I thought I could just remove the $today lines so that its just $file->base_name 
I however get errors. Not much of a coder. Any help would be greatly appreciated.

Changed above code to:
  ```
  protected function generateFilename(File $file)
    {
 $today = (new Carbon());
        $file->path = sprintf(
            "%s",
            $today->toDateString() . $today->micro . '-' . $file->base_name    $
    }
```
This removed the time stamp from the forum output, but the file still gets uploaded to S3-bucket with the time stamp. Where do I make the change to remove the timestamp from the file before it gets uploaded?

Maybe have an option to disable appending  a date and time stamp to the end of the file would remove future issues with characters .

Thank you. Have a happy Friday the 13th.

**Comment by Luceos** [comment]
I have been looking into this. Seems the call to AWS returns the URL to use as well. This has to be changed in the current AWS adapter implementation.

**Comment by 0E800** [comment]
Its peculiar. I got the file to upload without the time-stamp (which causes issues if someone uploads a file with the same name [the time stamp makes each file unique])
The link matches the link in the S3 bucket identically. 
If I copy the link from the S3 bucket and past it inside the Flarum post, it is displayed immediately. Like I said though, I compared both urls and they looks identical but the one that is created from the extension does not render.

I can provide screenshot / video-screen capture of workflow.

**Comment by Luceos** [comment]
I'm making some progress on this issue, I have to drop the illuminate filesystem implementation for that and directly implement league flysystem, which I had been doing already anyway. Keep you posted. @0E800

**Comment by Luceos** [comment]
This has to move up in priority now that we show previews and the AWS adapter is misbehaving.

**Comment by Luceos** [comment]
https://www.devroom.io/2010/12/24/public-readable-amazon-s3-bucket-policy/ required access policy
