### ISSUE TITLE
Extendability

### ISSUE THREAD

**Issue by dav-is** [flagrow/upload#45]
Add way for new methods to be added by 3rd party extensions. 

Example of use: using a custom method in a private extension.

**Comment by Luceos** [comment]
You mean custom adapters?

**Comment by dav-is** [comment]
Yes

**Comment by 0E800** [comment]
Not sure all 3rd party file hosting providers use the same auth.

Any resources that could help a dev get a head start with adding other providers would be awesome. Like a tutorial for creating just an imgur source would give people an idea of what is required. If wishes were free...

**Comment by Luceos** [comment]
@dav-is would it be sufficient to just show the adapter in the dropdown? It would be a lot more complicated to also allow the adapter to be configured within the extension..

**Comment by Luceos** [comment]
See [here](https://github.com/flagrow/upload/tree/custom-adapter#custom-adapters)

**Comment by dav-is** [comment]
Could use an event based system for loading adapters.

**Comment by dav-is** [comment]
> @dav-is would it be sufficient to just show the adapter in the dropdown? It would be a lot more complicated to also allow the adapter to be configured within the extension..
In my case, there won't be any user configuration as all the authentication keys will be inserted into the database at install, but I'm not sure about other cases.

**Comment by Luceos** [comment]
@dav-is your comment about Events made sense too btw. I'll take it into consideration, if you are up to it, feel free to PR it. Otherwise I'll have to make some time available to implement this a bit better.

Any ETA you need this @dav-is ?

**Comment by dav-is** [comment]
A month or two. Not a huge rush but I appreciate your consideration! :)

**Comment by Luceos** [comment]
@dav-is does [this event](https://github.com/flagrow/upload/blob/event-improvements/src/Commands/UploadHandler.php#L110) suffice? It allows you to assign any adapter whenever you like using event properties for conditionals.

**Comment by Luceos** [comment]
merged
