### ISSUE TITLE
Upload Images Error

### ISSUE THREAD

**Issue by AugmentBLU** [flagrow/upload#48]
Hello,

I'm having issues uploading files on my local server. I can see the image directory being created under `/assets/files/2017-01-28` when I attempt to upload a simple JPG, however I am receiving an error message. 

> Oops! Something went wrong. Please reload the page and try again.

I can see in the the following response which doesn't look correct.

`<br />
<fon`

Any idea what the issue could be? I'm logged in as an admin, I have the Permissions for Upload files set for Admin but the issue still appear.

I'm using the latest Flarum and Flagrow/upload versions.

Thanks!

**Comment by Luceos** [comment]
Did you enable debug in your config and see what message you get then (a debug button will show up on the oops message).

Can you tell me how you are hosting your app?

**Comment by AugmentBLU** [comment]
OK, just used the debug setting and it's pretty much the same output.

```
200 OK
POST http://flarum.app/api/flagrow/upload
<br />
<fon
```
I'm using Homestead/vagrant on Windows 10. I do have Flarum working properly so far, posting, sign up etc. I tried a couple other extensions but having problems with this uploading.

**Comment by Luceos** [comment]
There are no errors in your log files anywhere?

**Comment by AugmentBLU** [comment]
Unfortunately there's no errors appearing in the log. I just tried again and the same response is given, however there's no error appearing in the log. I also enabled debug mode and nothing more than I posted previously.

I tried to uninstall and now I see this.

```
500 Internal Server Error
POST http://flarum.app/api/extensions/flagrow-upload

<br />
<font size='1'
```

**Comment by Luceos** [comment]
There is an issue with directory separator under windows, this might affect you too, see #50

**Comment by Luceos** [comment]
Feel free to re-open if this is not solved or you have more information on how to reproduce.
