### ISSUE TITLE
Not possible to paste text when extension is enabled

### ISSUE THREAD

**Issue by chaosbunker** [flagrow/upload#60]
- flagrow/upload extension version: 0.4.7
- flarum version: 0.1.0-beta6
- Upload adapter causing issues:

The upload extension makes it impossible to paste text into the the text field when writing a post or creating a new discussion. This happens for me on macOS in chrome and Firefox, it works fine in safari 

---

...

**Comment by Luceos** [comment]
That sounds like quite the issue.

**Comment by Hekmon** [comment]
Same here with windows + chrome/firefox :)

**Comment by 0E800** [comment]
Also confirmed on Firefox (Win).

**Comment by blackjelly** [comment]
I also encountered this problem, after activation extension editor can not paste text.
