### ISSUE TITLE
Can not set the picture watermark, I use the png picture

### ISSUE THREAD

**Issue by blackjelly** [flagrow/upload#61]
- flagrow/upload extension version:0.4.7
- flarum version:v0.1.0-beta.6
- php version: 7.1.0
- Upload adapter causing issues:
Can not set the picture watermark，I use the png picture
---

...

**Comment by Luceos** [comment]
Any errors? Can you set any watermark at all? Can you verify the file is written to disk, it should show up in the `storage` directory as `watermark-<random>`?

**Comment by blackjelly** [comment]
There is this file watermark- <random>, but does not take effect, upload pictures and no watermark. I'm sure to turn on this option.

**Comment by Luceos** [comment]
Can you attach that watermark here, so I can test it out?

**Comment by blackjelly** [comment]
Is there a special requirement for the size of the image already? I do not know how to upload files here.

**Comment by Luceos** [comment]
You can use the clipboard. Or use the "selecting them" link with the composer screen of the message where you type comments here.

**Comment by blackjelly** [comment]
Thank you for your reply, I have solved, although I do not know where the problem is, I directly reinstall the entire flarum.
Finally, a small proposal, the watermark image can be displayed after uploading, and can adjust the transparency.
Thanks again！ Great plugin.

**Comment by Luceos** [comment]
Thanks, feel free to open a separate issue with your feature requests ;)

Happy to know you got it solved.
