### ISSUE TITLE
The images aren't upload to my Imgur account

### ISSUE THREAD

**Issue by aethior** [flagrow/upload#64]
- flagrow/upload extension version: 0.4.9
- flarum version: 0.1.0-beta.6
- Upload adapter causing issues: Imgur

---

When I upload an image using the extension the image is not upload to my imgur account. The upload is 'anonymous' (without associated user).

Disclaimer: Is the first time that I use Imgur, maybe I'm doing something wrong. My settings: http://imgur.com/a/EAMfd

**Comment by Luceos** [comment]
That should work. Just had imgur configured in my dev environment without issue. Please add more information if possible. Errors?
