### ISSUE TITLE
"Something went wrong while trying to load the full version of this site" 

### ISSUE THREAD

**Issue by acseven** [flagrow/upload#65]
- flagrow/upload extension version: 0.4.9
- flarum version: 0.1.0-beta.6
- Upload adapter causing issues: N/A

---

Hi,
I just created an empty Flarum forum and installed this extension. The issue is that it breaks the site after it has been enabled, returning an empty page with a text header and this notice:

> Something went wrong while trying to load the full version of this site 

I am able to make it work again by removing the plugin from the settings table. Also, I had installed another extension before _s9e/flarum-ext-mediaembed_, which loaded fine.

I'm looking to use this extension to test this SMF forum to Flarum migration tool:
https://github.com/ItalianSpaceAstronauticsAssociation/smf2_to_flarum

> $do_attachments_images = true;	// Requires flarum-image-upload ext.

While I'm at it, can you comment if it flagrow/upload it compatible with the query this tool is doing, and also if it would be feasible to use it to import other attachments, different from images? Here's the [code section pertaining attachments](https://github.com/ItalianSpaceAstronauticsAssociation/smf2_to_flarum/blob/master/smf2_to_flarum_alternative.php#L544)

Thank you

**Comment by 0E800** [comment]
After you installed the extension did you run¿:

`php flarum cache:clear`

On the device with the  rowser error, did you do a CTRL F5 refresh?

**Comment by Luceos** [comment]
> While I'm at it, can you comment if it flagrow/upload it compatible with the query this tool is doing, and also if it would be feasible to use it to import other attachments, different from images? Here's the code section pertaining attachments

It seems to work only with flagrow/flarum-ext-image-upload, not this extension. With some modification the script could however work with this extension and migrate all files, not just images.

Related to the rest, see the question @0E800 asks.

**Comment by acseven** [comment]
Hi,
I did run ```php flarum cache:clear``` and made sure local caching wasn't an issue (private nav browser and different browser).

_Right after activation:_
![scrn0](https://cloud.githubusercontent.com/assets/1176371/24243299/8b3ad780-0fb2-11e7-851c-f4aeb49aac00.png)

_When trying to accessing the forum itself directly:_
![scrn1](https://cloud.githubusercontent.com/assets/1176371/24243301/8e2e834c-0fb2-11e7-9af0-2548740d156b.png)

> It seems to work only with flagrow/flarum-ext-image-upload, not this extension. With some modification the script could however work with this extension and migrate all files, not just images.

Thanks for the input, I'll have a look at the script to see if I can make something out of it. I wasn't being able to install flagrow/flarum-ext-image-upload yesterday though, there was something about minimum versions and it wouldn't start, which it now did.

**Comment by Luceos** [comment]
Do you use cloudflare? If so flush that cache too.

**Comment by acseven** [comment]
> Do you use cloudflare? If so flush that cache too.

I do and I did purge its cache (and enabled dev mode), no difference though.

**Comment by Luceos** [comment]
Very weird are you able to provide the url or can you take a look at the webdeveloper console and your error log for your site?

**Comment by acseven** [comment]
How can I produce an error log related to this? The main error log doesn't contain anything related to it.

**Comment by acseven** [comment]
Note: enabling _'debug' => true_ in _config.php is making it run properly, but no errors are produced though. I'm looking at the console but nothing seems to ring a bell.

**Comment by Luceos** [comment]
If you disable debug again, does it work then?

**Comment by Luceos** [comment]
And what OS are you on? PHP version?

**Comment by acseven** [comment]
> If you disable debug again, does it work then?

Actually, yes, it does work after setting debug to false.

>  And what OS are you on? PHP version?

LiteSpeed V6.10
PHP 7.1.2

**Comment by Luceos** [comment]
There are some things that debug mode does. Like flushing caches etc. It's the first time I've heard such an issue to continue past a cache:clear etc.. Perhaps your permissions are wrong for the asset files or the cache directory.. If I'm not mistaken Flarum will not throw an error if it can't delete a cache file (js, css etc).

**Comment by acseven** [comment]
Ok, thanks for the help in any case. The debug info is useful for the time being.
