### ISSUE TITLE
Error when trying to download image

### ISSUE THREAD

**Issue by jtojnar** [flagrow/upload#82]
- flagrow/upload extension version: 0.5.0
- flarum version: 0.1.0-beta.6
- Upload adapter causing issues: local

I have disabled download logging.

```
2017/04/19 22:45:30 [error] 1708#1708: *2016 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: download in /var/www/forum/vendor/flagrow/upload/src/Commands/DownloadHandler.php on line 100" while reading response header from upstream, client: 147.251.211.124, server: xxx, request: "GET /api/flagrow/download/5ae1e98a-7f36-4c01-9019-52bc670d5eea/231/qo00gjAWzIx8trjbuH9MTE4vEFsMsbmP8a23gPfX HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "xxx", referrer: "xyz"
```

The relevant line: https://github.com/flagrow/upload/blob/7ce01cf6a80c494d07ad09953dbd5147f643d151/src/Commands/DownloadHandler.php#L100

**Comment by issyrocks12** [comment]
Looks like the variable isn't defined or, you meant $downloader

**Comment by Luceos** [comment]
Nope it was download, but if you disable download logging, the variable was not set.
