### ISSUE TITLE
Allow allowing download to everyone

### ISSUE THREAD

**Issue by jtojnar** [flagrow/upload#84]
- flagrow/upload extension version: 0.0.5
- flarum version: 0.1.0-beta.6

I would like everyone to be able to download files just like they can view the discussions.

**Comment by Luceos** [comment]
I considered this while publishing the version. Will be taken care of asap.

**Comment by jtojnar** [comment]
I have set it to everyone but it still produces an error:

```shell
curl https://ostrov-tucnaku.cz/api/flagrow/download/f29eb5cf-68c6-4471-a015-fafe06301850/231/9YOTlmfqCFlXZ2gYoo6pz00Wq0tcrDZw1rbjzK9p
{"errors":[{"status":"401","code":"permission_denied"}]}
```

**Comment by jtojnar** [comment]
I also disabled hotlink protection. Can that have something to do with this?

**Comment by Luceos** [comment]
Nope it seems this is not working as intended.

**Comment by jtojnar** [comment]
It does not work for me when not authenticated – see https://ostrov-tucnaku.cz/d/3-piskoviste/21
