### ISSUE TITLE
Clicking download button opens file thrice

### ISSUE THREAD

**Issue by jtojnar** [flagrow/upload#85]
- flagrow/upload extension version: 0.0.5
- flarum version: 0.1.0-beta.6

When I click on the download button, the link opens thrice.

Reproducible in Firefox Nightly and Firefox 52, even in private mode; cannot reproduce in Chromium.

**Comment by Luceos** [comment]
For images or files?

**Comment by Luceos** [comment]
Once tagged, please let me know whether this is fixed :grin:

**Comment by jtojnar** [comment]
I can still reproduce this after clearing cache.

**Comment by Luceos** [comment]
Does this behavior happen on files or images?

**Comment by Luceos** [comment]
Happens on chrome too if you disable popup blocking.
