### ISSUE TITLE
Display the entire image on the card

### ISSUE THREAD

**Issue by jtojnar** [flagrow/upload#88]
- flagrow/upload extension version: 0.5.3
- flarum version: 0.1.0-beta.6

---

On our fora, the most of uploaded images are mobile screenshots oriented as a portrait. Since the card is limited to the height of 250 px and width of 50%, only fraction of each captured scene is visible. Combined with the [lack of lightbox](https://github.com/flagrow/upload/issues/46) and [forced download](https://github.com/flagrow/upload/issues/87) users have no option to view the pictures other than downloading them.

For now, I added the following snippet to custom CSS. In the long term, a better solution should be found, though. Generating multiple thumbnails and displaying them [responsively](https://github.com/flagrow/upload/issues/69) would work.

```css
.flagrow-download .wrapper {
    background-size: contain !important;
}
```

P.S. It looks even weirder on mobile:

![](https://cloud.githubusercontent.com/assets/705123/25295431/b58cc76c-26e3-11e7-81eb-8b88b93ba9ab.png)

**Comment by Luceos** [comment]
Feel free to do a PR that allows showing more of the image.

**Comment by jrock17** [comment]
+1

I was a bit surprised to find the images don't show normal width in the posts and that the download button can't be turned off. I know this plug-in has a lot of features, but basic image uploading was easier in the previous upload plugin.

Would be great to disable downloads (and the overlay) and have the image appear actual width (or the width it was limited to when uploading).

**Comment by haydenjames** [comment]
`.flagrow-download .wrapper {
    background-size: contain !important;
}`

... that does not work for me. Images are still dumbfoundingly small.

**Comment by luceos** [comment]
Check 0.6 version.
